/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rube_xiba_native_RunScript */

#ifndef _Included_com_rube_xiba_native_RunScript
#define _Included_com_rube_xiba_native_RunScript
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rube_xiba_native_RunScript
 * Method:    runScript
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rube_xiba_1native_RunScript_runScript
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
