/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rube_xiba_native_NativeActivity */

#ifndef _Included_com_rube_xiba_native_NativeActivity
#define _Included_com_rube_xiba_native_NativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rube_xiba_native_NativeActivity
 * Method:    showToast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rube_xiba_1native_NativeActivity_showToast
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
